name: YouTube Shorts AI Auto

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Ambil kode repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg libavcodec-extra

      # 4️⃣ Install dependencies (MoviePy terbaru tanpa ImageMagick)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install moviepy==2.0.0.dev2 gTTS google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      # 5️⃣ Jalankan bot YouTube Shorts AI
      - name: Jalankan bot YouTube Shorts AI
        env:
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
        run: |
          echo "$CLIENT_SECRET_JSON" > client_secret.json
          python main.py

          python main.py
