name: YouTube Shorts AI Auto

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg libavcodec-extra

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install moviepy==1.0.3
        pip install -r requirements.txt

    - name: Jalankan bot YouTube Shorts AI
      env:
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
      run: |
        echo "$CLIENT_SECRET_JSON" > client_secret.json
        python main.py
